# Generated by Django 4.0.4 on 2022-07-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=122)),
                ('firstname', models.CharField(max_length=122)),
                ('middlename', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('emp_phone', models.CharField(max_length=12)),
                ('emp_email', models.CharField(max_length=122)),
                ('emp_designation', models.CharField(max_length=122)),
                ('emp_address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=122)),
                ('hospital_address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_type', models.CharField(max_length=122)),
                ('tariff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_Name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('password', models.TextField(max_length=122)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.employee')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='organisationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.hospital'),
        ),
    ]
