# Generated by Django 4.0.4 on 2022-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
