# Generated by Django 4.0.4 on 2022-07-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userrole_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_type', models.CharField(max_length=122)),
                ('tariff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=122)),
                ('availableday', models.CharField(max_length=122)),
                ('startsat', models.DateTimeField()),
                ('endsat', models.DateTimeField()),
                ('noofslots', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.employee')),
            ],
        ),
    ]
