# Generated by Django 4.0.4 on 2022-07-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_services_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=122)),
                ('prno', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patienthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevous_history', models.TextField(max_length=200)),
                ('previous_doctor_remarks', models.TextField(max_length=200)),
                ('cross_consultation', models.CharField(max_length=3)),
                ('previous_doctor_details', models.TextField(max_length=200)),
                ('patientdiagnosis', models.TextField(max_length=200)),
                ('finaldiagnosis', models.TextField(max_length=200)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
