# Generated by Django 4.0.4 on 2022-07-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_encounter_patientvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctorid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organisationid',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='patientid',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='encounterid',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='patientid',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='finaldiagnosis',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='patientdiagnosis',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='PatientVisit',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
